//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("api.Data.Resources.SqlQueries", typeof(SqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [AspNetRoles];.
        /// </summary>
        public static string DeleteRolesFromAspNetRoles {
            get {
                return ResourceManager.GetString("DeleteRolesFromAspNetRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [AspNetUserRoles];.
        /// </summary>
        public static string DeleteUsersRolesOnAspNetUserRoles {
            get {
                return ResourceManager.GetString("DeleteUsersRolesOnAspNetUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [AspNetRoles] ([Id], [Name]) VALUES (1, &apos;Admin&apos;);
        ///INSERT INTO [AspNetRoles] ([Id], [Name]) VALUES (2, &apos;User&apos;);.
        /// </summary>
        public static string InsertRolesToAspNetRoles {
            get {
                return ResourceManager.GetString("InsertRolesToAspNetRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [AspNetUserRoles] ([UserId], [RoleId])
        ///SELECT id,
        ///       CASE WHEN [UserName] = &apos;vbtestv@mail.ru&apos; THEN 1 ELSE 2 END AS RoleId
        ///FROM [AspNetUsers];.
        /// </summary>
        public static string SetRolesToUsersOnAspNetUserRoles {
            get {
                return ResourceManager.GetString("SetRolesToUsersOnAspNetUserRoles", resourceCulture);
            }
        }
    }
}
